name: Deploy on Comment

on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.issue.pull_request.head.ref }}
          token: ${{ secrets.GH_PAT_TOKEN }}

      - name: Deploy to gh-pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin gh-pages
          git checkout -b gh-pages origin/gh-pages
          mkdir -p build/${{ github.event.issue.number }}/
          cp -r package/* build/${{ github.event.issue.number }}/
          git add build/
          git commit -m "Deploy static files to gh-pages"
          git push origin gh-pages