name: Copy Package to deployBranch

on:
  issue_comment:
    types: [created]

jobs:
  copy_to_gh_pages:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT_TOKEN }}

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Deploy package to deployBranch
        run: |
          issue_number="${{ github.event.issue.number }}"
          repo_owner="${{ github.event.repository.owner.login }}"
          repo_name="${{ github.event.repository.name }}"
          issue_data=$(curl -s "https://api.github.com/repos/${repo_owner}/${repo_name}/pulls/${issue_number}")          
          # Extract branch information from issue data (adjust this based on the structure of your issue data)
          branch=$(echo "$issue_data" | jq -r '.head.ref')
          echo "Branch associated with the issue: $branch"
          git pull
          git checkout deployBranch
          git pull
          git checkout $branch
          git pull
          git checkout deployBranch
          mkdir -p build/${{ github.event.issue.number }}/
          git checkout $branch -- package
          cp -r package/* build/${{ github.event.issue.number }}/
          if [[ $(git status --porcelain) ]]; then
            git add build/
            git commit -m "Deploy static files"
            git push origin deployBranch
          else
            # If no changes, print a message
            echo "No changes to commit."
          fi
      - name: Comment on PR
        run: |
          COMMENT="Your comment goes here"
  
          # Use GitHub API to add a comment to the pull request
          curl -sSL -H "Authorization: Bearer ${{ secrets.GH_PAT_TOKEN }}" \
            -H "Content-Type: application/json" \
            -X POST -d "{\"body\":\"$COMMENT\"}" \
            "https://api.github.com/repos/${{ github.event.repository.name }}/issues/${{github.event.issue.number}}/comments"