name: Copy Package to deployBranch

on:
  issue_comment:
    types: [created]

jobs:
  copy_to_gh_pages:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT_TOKEN }}

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Get Pull Request Information
        id: pr
        run: |
          issue_number=$(echo "${{ github.event.issue.number }}")
          pr_info=$(curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    "https://api.github.com/repos/${{ github.repository }}/issues/${issue_number}")

          echo "::set-output name=pr_info::$pr_info"
  
      - name: Extract Branch Name
        run: |
          pr_url=$( steps.pr.outputs.pr_info | fromJSON | .pull_request.url )
          branch_name=$(basename $pr_url)
          echo "Branch name is: $branch_name"
      - name: Deploy package to deployBranch
        run: |
          git fetch
          git checkout deployBranch
          mkdir -p build/${{ github.event.issue.number }}/
          git checkout ${{github.event.ref}} -- package
          echo "Branch name is: ${{ toJson(github.event.repository.branches_url) }}"
          cp -r package/* build/${{ github.event.issue.number }}/
          git add build/
          git commit -m "Deploy static files"
          git push origin deployBranch
