name: Copy Package to gh-pages

on:
  push:
    branches:
      - branch1  # Change this to the source branch containing the package directory

jobs:
  copy_to_gh_pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Copy package to gh-pages
        run: |
          git checkout gh-pages
          mkdir -p pkg
          git checkout branch1 -- package
          cp -r package/* pkg/
          git add pkg
          git commit -m "Copy package contents from branch1 to gh-pages"
          git push origin gh-pages
