name: Copy Package to deployBranch

on:
  issue_comment:
    types: [created]

jobs:
  copy_to_gh_pages:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT_TOKEN }}

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Deploy package to deployBranch
        run: |
          git fetch
          git checkout deployBranch
          mkdir -p build/${{ github.event.issue.number }}/
          git checkout ${{github.event.ref}} -- package
          cp -r package/* build/${{ github.event.issue.number }}/
          git add build/
          git commit -m "Deploy static files"
          git push origin deployBranch
