name: "publish npm"

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - name: Configure Git Identity
        run: |
          git config --global user.email "ankitrastogichannel@gmail.com"
          git config --global user.name "ankitrastogi2"
        shell: bash
      - name: Update Package Version
        run: |
          # Increase the package version (for example, using a semantic versioning bump)
          npm version patch
          git add .
          git push https://${{secrets.GH_PAT_TOKEN}}@https://github.com/ankitrastogi2/cdn HEAD:main

        working-directory: package
      - name: Publish
        run: |
          # Publish the updated package
          npm publish --access public
        working-directory: package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
