name: "Publish package to npm"

on:
  push:
    branches:
      - main

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
              with:
                token: ${{ secrets.GH_PAT_TOKEN }}
                fetch-depth: 2
            - name: node
              uses: actions/setup-node@v2
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org
            - name: Increment package version
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                cd package/
                npm version patch -m "Increment package version to %s"
                git pull
                git add .
                git commit -m 'Updated version'
                git push
            - name: publish
              run: npm publish --access public
              working-directory: package
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

