name: "publish npm"

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - name: Configure Git Identity
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
        shell: bash
      - name: Update Package Version
        run: |
          # Increase the package version (for example, using a semantic versioning bump)
          npm version patch
        working-directory: package
      - name: Publish
        run: |
          # Publish the updated package
          npm publish --access public
        working-directory: package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
