name: "publish npm"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/build/**'
      - 'package/package.json'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
              with:
                token: ${{ secrets.GH_PAT_TOKEN }}
                fetch-depth: 2
            - name: node
              uses: actions/setup-node@v2
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org
            - name: Find React apps and Build
              run: |
                for DIR in package/*/ ; do
                  if git diff --name-only HEAD^ HEAD | grep -q "^$DIR"; then
                    if [ -f "$DIR/package.json" ]; then
                      echo "Building React app in $DIR"
                      (cd $DIR && npm install && npm run build -- --output-path ./build)
                    else
                      echo "$DIR is not a React app."
                    fi
                  else
                    echo "No changes detected in $DIR"
                  fi
                done
            - name: Commit and Push Changes
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git pull
                git add .
                git commit -m "Automated build commit" -a || echo "No changes to commit"
                git push
            - name: Increment package version
              run: |
                cd package/
                npm version patch -m "Increment package version to %s"
                git pull
                git add .
                git commit -m 'Updated version'
                git push
            - name: publish
              run: npm publish --access public
              working-directory: package
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
