name: "publish npm"

on:
  push:
    branches:
      - main

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
              with:
                token: ${{ secrets.GH_PAT_TOKEN }}
            - name: node
              uses: actions/setup-node@v2
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org
            - name: Configure Git Identity
              run: |
                git config --global user.email "you@example.com"
                git config --global user.name "Your Name"
              shell: bash
            - name: Find React apps and Build
              run: |
                for DIR in package/*/ ; do
                  if [ -f "$DIR/package.json" ]; then
                  echo "Building React app in $DIR"
                  # Change the build script as needed to specify the output directory
                  (cd $DIR && npm install && npm run build -- --output-path ./build)
                  else
                    echo "$DIR is not a React app."
                  fi
                done
            - name: Commit and Push Changes
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add .
                git commit -m "Automated build commit" -a || echo "No changes to commit"
                git push
            - name: Increment package version
              run: |
                npm version patch -m "Increment package version to %s"
                git push
            - name: publish
              run: npm publish --access public
              working-directory: package
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
